- hosts: tag_Name_nginx
  user : ec2-user
  become : true   
  tasks:
    - name : "install ngi"
      yum : 
        name : nginx
        state : latest
        

    - name: Start NGiNX
      service:
        name: nginx
        state: started 
